#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SERVICES_DIR="$ROOT_DIR/ops/op-stack/hc002/services"
ROOT_ENV_FILE="$ROOT_DIR/.env"
DEPLOYER_ENV_FILE="$ROOT_DIR/ops/op-stack/hc002/deployer/.env"
DEPLOY_SUMMARY="$ROOT_DIR/ops/op-stack/hc002/deployer/deployment.summary.json"
ROLLUP_FILE="$ROOT_DIR/ops/op-stack/hc002/deployer/rollup.json"
SERVICES_ENV="$SERVICES_DIR/.env"
BRIDGE_CONFIG="$SERVICES_DIR/bridge-ui/bridge-config.json"

is_placeholder() {
  local v="${1:-}"
  [[ -z "$v" || "$v" =~ REPLACE|YOUR_|your_|example|placeholder ]]
}

# shellcheck source=/dev/null
if [[ -f "$ROOT_ENV_FILE" ]]; then
  source "$ROOT_ENV_FILE"
fi

# shellcheck source=/dev/null
if [[ -f "$DEPLOYER_ENV_FILE" ]]; then
  source "$DEPLOYER_ENV_FILE"
fi

if [[ ! -s "$DEPLOY_SUMMARY" || ! -s "$ROLLUP_FILE" ]]; then
  echo "Missing deployer artifacts:"
  echo "  - $DEPLOY_SUMMARY"
  echo "  - $ROLLUP_FILE"
  echo "Run HC-002 deployer flow first."
  exit 1
fi

if ! is_placeholder "${FAUCET_PRIVATE_KEY:-}"; then
  FAUCET_KEY_EFFECTIVE="$FAUCET_PRIVATE_KEY"
elif ! is_placeholder "${PRIVATE_KEY:-}"; then
  FAUCET_KEY_EFFECTIVE="$PRIVATE_KEY"
else
  FAUCET_KEY_EFFECTIVE="${DEPLOYER_PRIVATE_KEY:-}"
fi

if [[ -n "$FAUCET_KEY_EFFECTIVE" && ! "$FAUCET_KEY_EFFECTIVE" =~ ^0x ]]; then
  FAUCET_KEY_EFFECTIVE="0x$FAUCET_KEY_EFFECTIVE"
fi

if [[ ! "$FAUCET_KEY_EFFECTIVE" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  echo "Invalid faucet key. Set FAUCET_PRIVATE_KEY in root .env or provide PRIVATE_KEY/DEPLOYER_PRIVATE_KEY."
  exit 1
fi

CLEAR_CHAIN_ID="$(jq -r '.chainId // .network.chainId' "$DEPLOY_SUMMARY")"
CLEAR_CHAIN_NAME="$(jq -r '.networkName // .network.name' "$DEPLOY_SUMMARY")"
L1_CHAIN_ID="$(jq -r '.l1ChainId // .network.l1ChainId' "$DEPLOY_SUMMARY")"

OPTIMISM_PORTAL_PROXY="$(jq -r '.l1Contracts.optimismPortalProxy // .contracts.optimismPortalProxy' "$DEPLOY_SUMMARY")"
L1_STANDARD_BRIDGE_PROXY="$(jq -r '.l1Contracts.l1StandardBridgeProxy // .contracts.l1StandardBridgeProxy' "$DEPLOY_SUMMARY")"
L1_CROSS_DOMAIN_MESSENGER_PROXY="$(jq -r '.l1Contracts.l1CrossDomainMessengerProxy // .contracts.l1CrossDomainMessengerProxy' "$DEPLOY_SUMMARY")"
L1_ERC721_BRIDGE_PROXY="$(jq -r '.l1Contracts.l1Erc721BridgeProxy // .contracts.l1Erc721BridgeProxy' "$DEPLOY_SUMMARY")"
SYSTEM_CONFIG_PROXY="$(jq -r '.l1Contracts.systemConfigProxy // .contracts.systemConfigProxy' "$DEPLOY_SUMMARY")"

FAUCET_PORT="${FAUCET_PORT:-8090}"
FAUCET_DRIP_AMOUNT_ETH="${FAUCET_DRIP_AMOUNT_ETH:-0.01}"
FAUCET_COOLDOWN_SECONDS="${FAUCET_COOLDOWN_SECONDS:-86400}"
SERVICES_PORT="${SERVICES_PORT:-8077}"
BLOCKSCOUT_HOST="${BLOCKSCOUT_HOST:-127.0.0.1}"
BLOCKSCOUT_PROTOCOL="${BLOCKSCOUT_PROTOCOL:-http}"
BLOCKSCOUT_SECRET_KEY_BASE="${BLOCKSCOUT_SECRET_KEY_BASE:-}"

if [[ -z "$BLOCKSCOUT_SECRET_KEY_BASE" || "$BLOCKSCOUT_SECRET_KEY_BASE" =~ REPLACE ]]; then
  BLOCKSCOUT_SECRET_KEY_BASE="$(openssl rand -hex 32)"
fi

mkdir -p "$SERVICES_DIR/bridge-ui"

cat >"$SERVICES_ENV" <<EOF
# Auto-generated by scripts/op-stack/hc002-services-init.sh
CLEAR_CHAIN_NAME="$CLEAR_CHAIN_NAME"
CLEAR_CHAIN_ID=$CLEAR_CHAIN_ID
CLEAR_COIN_SYMBOL=ETH
CLEAR_COIN_NAME="Sepolia ETH"

RPC_URL=http://127.0.0.1:9545
SERVICES_PORT=$SERVICES_PORT

BLOCKSCOUT_PROTOCOL=$BLOCKSCOUT_PROTOCOL
BLOCKSCOUT_HOST=$BLOCKSCOUT_HOST
BLOCKSCOUT_SECRET_KEY_BASE=$BLOCKSCOUT_SECRET_KEY_BASE

FAUCET_PORT=$FAUCET_PORT
FAUCET_DRIP_AMOUNT_ETH=$FAUCET_DRIP_AMOUNT_ETH
FAUCET_COOLDOWN_SECONDS=$FAUCET_COOLDOWN_SECONDS
FAUCET_PRIVATE_KEY=$FAUCET_KEY_EFFECTIVE
EOF

chmod 600 "$SERVICES_ENV"

cat >"$BRIDGE_CONFIG" <<EOF
{
  "chainName": "$CLEAR_CHAIN_NAME",
  "chainId": $CLEAR_CHAIN_ID,
  "l1ChainId": $L1_CHAIN_ID,
  "rpcUrl": "http://127.0.0.1:9545",
  "explorerUrl": "http://127.0.0.1:4000",
  "faucetUrl": "http://127.0.0.1:$FAUCET_PORT",
  "contracts": {
    "optimismPortalProxy": "$OPTIMISM_PORTAL_PROXY",
    "l1StandardBridgeProxy": "$L1_STANDARD_BRIDGE_PROXY",
    "l1CrossDomainMessengerProxy": "$L1_CROSS_DOMAIN_MESSENGER_PROXY",
    "l1Erc721BridgeProxy": "$L1_ERC721_BRIDGE_PROXY",
    "systemConfigProxy": "$SYSTEM_CONFIG_PROXY"
  }
}
EOF

echo "HC-002 services config initialized:"
echo "  - $SERVICES_ENV"
echo "  - $BRIDGE_CONFIG"
echo
echo "Next step:"
echo "  npm run hc002:services:start"
