#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/ops/op-stack/hc002/runtime/sequencer"
DEPLOYER_DIR="$ROOT_DIR/ops/op-stack/hc002/deployer"
ROOT_ENV_FILE="$ROOT_DIR/.env"
DEPLOYER_ENV_FILE="$DEPLOYER_DIR/.env"
GENESIS_SRC="$DEPLOYER_DIR/genesis.json"
ROLLUP_SRC="$DEPLOYER_DIR/rollup.json"
STATE_SRC="$DEPLOYER_DIR/state.applied.json"
GENESIS_DEST="$RUNTIME_DIR/genesis.json"
ROLLUP_DEST="$RUNTIME_DIR/rollup.json"
ENV_DEST="$RUNTIME_DIR/.env"
JWT_DEST="$RUNTIME_DIR/jwt.txt"

is_placeholder() {
  local v="${1:-}"
  [[ -z "$v" || "$v" =~ REPLACE|YOUR_|your_|example|placeholder ]]
}

if [[ ! -s "$GENESIS_SRC" || ! -s "$ROLLUP_SRC" || ! -s "$STATE_SRC" ]]; then
  echo "Missing HC-002 deployer artifacts."
  echo "Expected:"
  echo "  - $GENESIS_SRC"
  echo "  - $ROLLUP_SRC"
  echo "  - $STATE_SRC"
  echo "Run: npm run hc002:apply && npm run hc002:artifacts"
  exit 1
fi

# shellcheck source=/dev/null
if [[ -f "$ROOT_ENV_FILE" ]]; then
  source "$ROOT_ENV_FILE"
fi

# shellcheck source=/dev/null
if [[ -f "$DEPLOYER_ENV_FILE" ]]; then
  source "$DEPLOYER_ENV_FILE"
fi

if ! is_placeholder "${L1_RPC_URL:-}"; then
  L1_RPC_URL_EFFECTIVE="$L1_RPC_URL"
elif ! is_placeholder "${SEPOLIA_RPC_URL:-}"; then
  L1_RPC_URL_EFFECTIVE="$SEPOLIA_RPC_URL"
else
  L1_RPC_URL_EFFECTIVE="${ETH_SEPOLIA_RPC_URL:-}"
fi

if ! is_placeholder "${PRIVATE_KEY:-}"; then
  PRIVATE_KEY_EFFECTIVE="$PRIVATE_KEY"
else
  PRIVATE_KEY_EFFECTIVE="${DEPLOYER_PRIVATE_KEY:-}"
fi

if [[ -n "$PRIVATE_KEY_EFFECTIVE" && ! "$PRIVATE_KEY_EFFECTIVE" =~ ^0x ]]; then
  PRIVATE_KEY_EFFECTIVE="0x$PRIVATE_KEY_EFFECTIVE"
fi

if is_placeholder "$L1_RPC_URL_EFFECTIVE"; then
  echo "Invalid L1 RPC URL. Set L1_RPC_URL in $DEPLOYER_ENV_FILE or root .env."
  exit 1
fi

if [[ ! "$PRIVATE_KEY_EFFECTIVE" =~ ^0x[0-9a-fA-F]{64}$ ]] || [[ "$PRIVATE_KEY_EFFECTIVE" =~ ^0x0+$ ]]; then
  echo "Invalid private key. Set PRIVATE_KEY in $DEPLOYER_ENV_FILE or DEPLOYER_PRIVATE_KEY in root .env."
  exit 1
fi

L1_BEACON_URL_EFFECTIVE="${L1_BEACON_URL:-https://ethereum-sepolia-beacon-api.publicnode.com}"
P2P_ADVERTISE_IP_EFFECTIVE="${P2P_ADVERTISE_IP:-127.0.0.1}"

BATCH_INBOX_ADDRESS="$(jq -r '.batch_inbox_address // empty' "$ROLLUP_SRC")"
GAME_FACTORY_ADDRESS="$(jq -r '.opChainDeployments[0].DisputeGameFactoryProxy // empty' "$STATE_SRC")"

if [[ ! "$BATCH_INBOX_ADDRESS" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
  echo "Unable to parse batch inbox address from $ROLLUP_SRC"
  exit 1
fi

if [[ ! "$GAME_FACTORY_ADDRESS" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
  echo "Unable to parse DisputeGameFactory proxy from $STATE_SRC"
  exit 1
fi

mkdir -p "$RUNTIME_DIR"
cp "$GENESIS_SRC" "$GENESIS_DEST"
cp "$ROLLUP_SRC" "$ROLLUP_DEST"

if [[ ! -f "$JWT_DEST" ]]; then
  openssl rand -hex 32 >"$JWT_DEST"
  chmod 600 "$JWT_DEST"
fi

cat >"$ENV_DEST" <<EOF
# Auto-generated by scripts/op-stack/hc002-runtime-init.sh
# Runtime: Clear Testnet (chainId 92373)

L1_RPC_URL=$L1_RPC_URL_EFFECTIVE
L1_BEACON_URL=$L1_BEACON_URL_EFFECTIVE
PRIVATE_KEY=$PRIVATE_KEY_EFFECTIVE
P2P_ADVERTISE_IP=$P2P_ADVERTISE_IP_EFFECTIVE

OP_BATCHER_L1_ETH_RPC=$L1_RPC_URL_EFFECTIVE
OP_BATCHER_PRIVATE_KEY=$PRIVATE_KEY_EFFECTIVE
OP_BATCHER_L2_ETH_RPC=http://op-geth:8545
OP_BATCHER_ROLLUP_RPC=http://op-node:8547
OP_BATCHER_BATCH_INBOX_ADDR=$BATCH_INBOX_ADDRESS
OP_BATCHER_POLL_INTERVAL=1s
OP_BATCHER_SUB_SAFETY_MARGIN=6
OP_BATCHER_NUM_CONFIRMATIONS=1
OP_BATCHER_SAFE_ABORT_NONCE_TOO_LOW_COUNT=3
OP_BATCHER_MAX_CHANNEL_DURATION=1
OP_BATCHER_DATA_AVAILABILITY_TYPE=calldata
OP_BATCHER_RPC_PORT=8548

OP_PROPOSER_L1_ETH_RPC=$L1_RPC_URL_EFFECTIVE
OP_PROPOSER_ROLLUP_RPC=http://op-node:8547
OP_PROPOSER_GAME_FACTORY_ADDRESS=$GAME_FACTORY_ADDRESS
OP_PROPOSER_PRIVATE_KEY=$PRIVATE_KEY_EFFECTIVE
OP_PROPOSER_PROPOSAL_INTERVAL=3600s
OP_PROPOSER_GAME_TYPE=0
OP_PROPOSER_POLL_INTERVAL=20s
OP_PROPOSER_ALLOW_NON_FINALIZED=true
OP_PROPOSER_WAIT_NODE_SYNC=true
EOF

chmod 600 "$ENV_DEST"

echo "HC-002 runtime initialized:"
echo "  - $GENESIS_DEST"
echo "  - $ROLLUP_DEST"
echo "  - $JWT_DEST"
echo "  - $ENV_DEST"
echo
echo "Next step:"
echo "  npm run hc002:runtime:start"
