/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IFundManager {
  export type DeedMintDataStruct = {
    assetType: BigNumberish;
    ipfsDetailsHash: string;
    definition: string;
    configuration: string;
    validatorContract: AddressLike;
    token: AddressLike;
  };

  export type DeedMintDataStructOutput = [
    assetType: bigint,
    ipfsDetailsHash: string,
    definition: string,
    configuration: string,
    validatorContract: string,
    token: string
  ] & {
    assetType: bigint;
    ipfsDetailsHash: string;
    definition: string;
    configuration: string;
    validatorContract: string;
    token: string;
  };
}

export interface IFundManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commissionPercentage"
      | "deedNFT"
      | "feeReceiver"
      | "formatFee"
      | "getCommissionBalance"
      | "getCommissionPercentage"
      | "mintBatchDeedNFT"
      | "mintDeedNFT"
      | "setCommissionPercentage"
      | "setDeedNFT"
      | "setFeeReceiver"
      | "setValidatorRegistry"
      | "validatorRegistry"
      | "withdrawValidatorFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommissionPercentageUpdated"
      | "DeedMinted"
      | "DeedNFTUpdated"
      | "FeeReceiverUpdated"
      | "ServiceFeeCollected"
      | "ValidatorFeesWithdrawn"
      | "ValidatorRegistryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commissionPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deedNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "formatFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommissionBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommissionPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchDeedNFT",
    values: [IFundManager.DeedMintDataStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintDeedNFT",
    values: [
      AddressLike,
      BigNumberish,
      string,
      string,
      string,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommissionPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidatorRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawValidatorFees",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commissionPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deedNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "formatFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommissionBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommissionPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCommissionPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDeedNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidatorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawValidatorFees",
    data: BytesLike
  ): Result;
}

export namespace CommissionPercentageUpdatedEvent {
  export type InputTuple = [newCommissionPercentage: BigNumberish];
  export type OutputTuple = [newCommissionPercentage: bigint];
  export interface OutputObject {
    newCommissionPercentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeedMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    owner: AddressLike,
    validator: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, owner: string, validator: string];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeedNFTUpdatedEvent {
  export type InputTuple = [newDeedNFT: AddressLike];
  export type OutputTuple = [newDeedNFT: string];
  export interface OutputObject {
    newDeedNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceiverUpdatedEvent {
  export type InputTuple = [newFeeReceiver: AddressLike];
  export type OutputTuple = [newFeeReceiver: string];
  export interface OutputObject {
    newFeeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceFeeCollectedEvent {
  export type InputTuple = [
    validator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    commission: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    token: string,
    amount: bigint,
    commission: bigint
  ];
  export interface OutputObject {
    validator: string;
    token: string;
    amount: bigint;
    commission: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorFeesWithdrawnEvent {
  export type InputTuple = [
    validator: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    validator: string,
    token: string,
    amount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    validator: string;
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegistryUpdatedEvent {
  export type InputTuple = [newValidatorRegistry: AddressLike];
  export type OutputTuple = [newValidatorRegistry: string];
  export interface OutputObject {
    newValidatorRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFundManager extends BaseContract {
  connect(runner?: ContractRunner | null): IFundManager;
  waitForDeployment(): Promise<this>;

  interface: IFundManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commissionPercentage: TypedContractMethod<[], [bigint], "view">;

  deedNFT: TypedContractMethod<[], [string], "view">;

  feeReceiver: TypedContractMethod<[], [string], "view">;

  formatFee: TypedContractMethod<[amount: BigNumberish], [string], "view">;

  getCommissionBalance: TypedContractMethod<
    [validatorContract: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getCommissionPercentage: TypedContractMethod<[], [bigint], "view">;

  mintBatchDeedNFT: TypedContractMethod<
    [deeds: IFundManager.DeedMintDataStruct[]],
    [bigint[]],
    "nonpayable"
  >;

  mintDeedNFT: TypedContractMethod<
    [
      owner: AddressLike,
      assetType: BigNumberish,
      ipfsDetailsHash: string,
      definition: string,
      configuration: string,
      validatorContract: AddressLike,
      token: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  setCommissionPercentage: TypedContractMethod<
    [_percentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDeedNFT: TypedContractMethod<
    [_deedNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeReceiver: TypedContractMethod<
    [_feeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setValidatorRegistry: TypedContractMethod<
    [_validatorRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  validatorRegistry: TypedContractMethod<[], [string], "view">;

  withdrawValidatorFees: TypedContractMethod<
    [validatorContract: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commissionPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deedNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "formatFee"
  ): TypedContractMethod<[amount: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCommissionBalance"
  ): TypedContractMethod<
    [validatorContract: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommissionPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintBatchDeedNFT"
  ): TypedContractMethod<
    [deeds: IFundManager.DeedMintDataStruct[]],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintDeedNFT"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      assetType: BigNumberish,
      ipfsDetailsHash: string,
      definition: string,
      configuration: string,
      validatorContract: AddressLike,
      token: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCommissionPercentage"
  ): TypedContractMethod<[_percentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDeedNFT"
  ): TypedContractMethod<[_deedNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeReceiver"
  ): TypedContractMethod<[_feeReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidatorRegistry"
  ): TypedContractMethod<
    [_validatorRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawValidatorFees"
  ): TypedContractMethod<
    [validatorContract: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommissionPercentageUpdated"
  ): TypedContractEvent<
    CommissionPercentageUpdatedEvent.InputTuple,
    CommissionPercentageUpdatedEvent.OutputTuple,
    CommissionPercentageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeedMinted"
  ): TypedContractEvent<
    DeedMintedEvent.InputTuple,
    DeedMintedEvent.OutputTuple,
    DeedMintedEvent.OutputObject
  >;
  getEvent(
    key: "DeedNFTUpdated"
  ): TypedContractEvent<
    DeedNFTUpdatedEvent.InputTuple,
    DeedNFTUpdatedEvent.OutputTuple,
    DeedNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceiverUpdated"
  ): TypedContractEvent<
    FeeReceiverUpdatedEvent.InputTuple,
    FeeReceiverUpdatedEvent.OutputTuple,
    FeeReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceFeeCollected"
  ): TypedContractEvent<
    ServiceFeeCollectedEvent.InputTuple,
    ServiceFeeCollectedEvent.OutputTuple,
    ServiceFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorFeesWithdrawn"
  ): TypedContractEvent<
    ValidatorFeesWithdrawnEvent.InputTuple,
    ValidatorFeesWithdrawnEvent.OutputTuple,
    ValidatorFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistryUpdated"
  ): TypedContractEvent<
    ValidatorRegistryUpdatedEvent.InputTuple,
    ValidatorRegistryUpdatedEvent.OutputTuple,
    ValidatorRegistryUpdatedEvent.OutputObject
  >;

  filters: {
    "CommissionPercentageUpdated(uint256)": TypedContractEvent<
      CommissionPercentageUpdatedEvent.InputTuple,
      CommissionPercentageUpdatedEvent.OutputTuple,
      CommissionPercentageUpdatedEvent.OutputObject
    >;
    CommissionPercentageUpdated: TypedContractEvent<
      CommissionPercentageUpdatedEvent.InputTuple,
      CommissionPercentageUpdatedEvent.OutputTuple,
      CommissionPercentageUpdatedEvent.OutputObject
    >;

    "DeedMinted(uint256,address,address)": TypedContractEvent<
      DeedMintedEvent.InputTuple,
      DeedMintedEvent.OutputTuple,
      DeedMintedEvent.OutputObject
    >;
    DeedMinted: TypedContractEvent<
      DeedMintedEvent.InputTuple,
      DeedMintedEvent.OutputTuple,
      DeedMintedEvent.OutputObject
    >;

    "DeedNFTUpdated(address)": TypedContractEvent<
      DeedNFTUpdatedEvent.InputTuple,
      DeedNFTUpdatedEvent.OutputTuple,
      DeedNFTUpdatedEvent.OutputObject
    >;
    DeedNFTUpdated: TypedContractEvent<
      DeedNFTUpdatedEvent.InputTuple,
      DeedNFTUpdatedEvent.OutputTuple,
      DeedNFTUpdatedEvent.OutputObject
    >;

    "FeeReceiverUpdated(address)": TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;
    FeeReceiverUpdated: TypedContractEvent<
      FeeReceiverUpdatedEvent.InputTuple,
      FeeReceiverUpdatedEvent.OutputTuple,
      FeeReceiverUpdatedEvent.OutputObject
    >;

    "ServiceFeeCollected(address,address,uint256,uint256)": TypedContractEvent<
      ServiceFeeCollectedEvent.InputTuple,
      ServiceFeeCollectedEvent.OutputTuple,
      ServiceFeeCollectedEvent.OutputObject
    >;
    ServiceFeeCollected: TypedContractEvent<
      ServiceFeeCollectedEvent.InputTuple,
      ServiceFeeCollectedEvent.OutputTuple,
      ServiceFeeCollectedEvent.OutputObject
    >;

    "ValidatorFeesWithdrawn(address,address,uint256,address)": TypedContractEvent<
      ValidatorFeesWithdrawnEvent.InputTuple,
      ValidatorFeesWithdrawnEvent.OutputTuple,
      ValidatorFeesWithdrawnEvent.OutputObject
    >;
    ValidatorFeesWithdrawn: TypedContractEvent<
      ValidatorFeesWithdrawnEvent.InputTuple,
      ValidatorFeesWithdrawnEvent.OutputTuple,
      ValidatorFeesWithdrawnEvent.OutputObject
    >;

    "ValidatorRegistryUpdated(address)": TypedContractEvent<
      ValidatorRegistryUpdatedEvent.InputTuple,
      ValidatorRegistryUpdatedEvent.OutputTuple,
      ValidatorRegistryUpdatedEvent.OutputObject
    >;
    ValidatorRegistryUpdated: TypedContractEvent<
      ValidatorRegistryUpdatedEvent.InputTuple,
      ValidatorRegistryUpdatedEvent.OutputTuple,
      ValidatorRegistryUpdatedEvent.OutputObject
    >;
  };
}
