/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCompatibleDeedNFT"
      | "addFieldRequirementsBatch"
      | "addWhitelistedToken"
      | "clearFieldRequirements"
      | "defaultOperatingAgreement"
      | "getRoleAdmin"
      | "getRoyaltyFeePercentage"
      | "getRoyaltyReceiver"
      | "getServiceFee"
      | "getValidationCriteria"
      | "grantRole"
      | "hasRole"
      | "isCompatibleDeedNFT"
      | "isTokenWhitelisted"
      | "operatingAgreementName"
      | "registerOperatingAgreement"
      | "removeCompatibleDeedNFT"
      | "removeWhitelistedToken"
      | "renounceRole"
      | "revokeRole"
      | "setPrimaryDeedNFT"
      | "setRoyaltyFeePercentage"
      | "setRoyaltyReceiver"
      | "setServiceFee"
      | "setValidationCriteria"
      | "supportsAssetType"
      | "tokenURI"
      | "validateDeed"
      | "validateOperatingAgreement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompatibleDeedNFTUpdated"
      | "DeedNFTUpdated"
      | "DeedValidated"
      | "DefaultOperatingAgreementUpdated"
      | "FieldRequirementAdded"
      | "FieldRequirementsCleared"
      | "OperatingAgreementRegistered"
      | "PrimaryDeedNFTUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ServiceFeeUpdated"
      | "TokenWhitelistStatusUpdated"
      | "ValidationCriteriaUpdated"
      | "ValidationError"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCompatibleDeedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addFieldRequirementsBatch",
    values: [BigNumberish, string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addWhitelistedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clearFieldRequirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultOperatingAgreement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoyaltyFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoyaltyReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getServiceFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationCriteria",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompatibleDeedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operatingAgreementName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOperatingAgreement",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCompatibleDeedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhitelistedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrimaryDeedNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltyFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltyReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidationCriteria",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsAssetType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateDeed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOperatingAgreement",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCompatibleDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFieldRequirementsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWhitelistedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearFieldRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultOperatingAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoyaltyFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoyaltyReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getServiceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationCriteria",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCompatibleDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatingAgreementName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOperatingAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCompatibleDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhitelistedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPrimaryDeedNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltyFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltyReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidationCriteria",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsAssetType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateDeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOperatingAgreement",
    data: BytesLike
  ): Result;
}

export namespace CompatibleDeedNFTUpdatedEvent {
  export type InputTuple = [deedNFTAddress: AddressLike, isCompatible: boolean];
  export type OutputTuple = [deedNFTAddress: string, isCompatible: boolean];
  export interface OutputObject {
    deedNFTAddress: string;
    isCompatible: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeedNFTUpdatedEvent {
  export type InputTuple = [newDeedNFT: AddressLike];
  export type OutputTuple = [newDeedNFT: string];
  export interface OutputObject {
    newDeedNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeedValidatedEvent {
  export type InputTuple = [tokenId: BigNumberish, isValid: boolean];
  export type OutputTuple = [tokenId: bigint, isValid: boolean];
  export interface OutputObject {
    tokenId: bigint;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultOperatingAgreementUpdatedEvent {
  export type InputTuple = [uri: string];
  export type OutputTuple = [uri: string];
  export interface OutputObject {
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FieldRequirementAddedEvent {
  export type InputTuple = [
    assetTypeId: BigNumberish,
    criteriaField: string,
    definitionField: string
  ];
  export type OutputTuple = [
    assetTypeId: bigint,
    criteriaField: string,
    definitionField: string
  ];
  export interface OutputObject {
    assetTypeId: bigint;
    criteriaField: string;
    definitionField: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FieldRequirementsClearedEvent {
  export type InputTuple = [assetTypeId: BigNumberish];
  export type OutputTuple = [assetTypeId: bigint];
  export interface OutputObject {
    assetTypeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatingAgreementRegisteredEvent {
  export type InputTuple = [uri: string, name: string];
  export type OutputTuple = [uri: string, name: string];
  export interface OutputObject {
    uri: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrimaryDeedNFTUpdatedEvent {
  export type InputTuple = [deedNFTAddress: AddressLike];
  export type OutputTuple = [deedNFTAddress: string];
  export interface OutputObject {
    deedNFTAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceFeeUpdatedEvent {
  export type InputTuple = [token: AddressLike, fee: BigNumberish];
  export type OutputTuple = [token: string, fee: bigint];
  export interface OutputObject {
    token: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWhitelistStatusUpdatedEvent {
  export type InputTuple = [token: AddressLike, status: boolean];
  export type OutputTuple = [token: string, status: boolean];
  export interface OutputObject {
    token: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationCriteriaUpdatedEvent {
  export type InputTuple = [assetTypeId: BigNumberish, criteria: string];
  export type OutputTuple = [assetTypeId: bigint, criteria: string];
  export interface OutputObject {
    assetTypeId: bigint;
    criteria: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationErrorEvent {
  export type InputTuple = [tokenId: BigNumberish, errorMessage: string];
  export type OutputTuple = [tokenId: bigint, errorMessage: string];
  export interface OutputObject {
    tokenId: bigint;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IValidator extends BaseContract {
  connect(runner?: ContractRunner | null): IValidator;
  waitForDeployment(): Promise<this>;

  interface: IValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCompatibleDeedNFT: TypedContractMethod<
    [deedNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  addFieldRequirementsBatch: TypedContractMethod<
    [
      assetTypeId: BigNumberish,
      criteriaFields: string[],
      definitionFields: string[]
    ],
    [void],
    "nonpayable"
  >;

  addWhitelistedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  clearFieldRequirements: TypedContractMethod<
    [assetTypeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  defaultOperatingAgreement: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoyaltyFeePercentage: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getRoyaltyReceiver: TypedContractMethod<[], [string], "view">;

  getServiceFee: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getValidationCriteria: TypedContractMethod<
    [assetTypeId: BigNumberish],
    [string],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isCompatibleDeedNFT: TypedContractMethod<
    [deedNFT: AddressLike],
    [boolean],
    "view"
  >;

  isTokenWhitelisted: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  operatingAgreementName: TypedContractMethod<[uri: string], [string], "view">;

  registerOperatingAgreement: TypedContractMethod<
    [uri: string, name: string],
    [void],
    "nonpayable"
  >;

  removeCompatibleDeedNFT: TypedContractMethod<
    [deedNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  removeWhitelistedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrimaryDeedNFT: TypedContractMethod<
    [deedNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setRoyaltyFeePercentage: TypedContractMethod<
    [percentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRoyaltyReceiver: TypedContractMethod<
    [receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setServiceFee: TypedContractMethod<
    [token: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setValidationCriteria: TypedContractMethod<
    [assetTypeId: BigNumberish, criteria: string],
    [void],
    "nonpayable"
  >;

  supportsAssetType: TypedContractMethod<
    [assetTypeId: BigNumberish],
    [boolean],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  validateDeed: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  validateOperatingAgreement: TypedContractMethod<
    [operatingAgreement: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCompatibleDeedNFT"
  ): TypedContractMethod<[deedNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addFieldRequirementsBatch"
  ): TypedContractMethod<
    [
      assetTypeId: BigNumberish,
      criteriaFields: string[],
      definitionFields: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addWhitelistedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearFieldRequirements"
  ): TypedContractMethod<[assetTypeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultOperatingAgreement"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoyaltyFeePercentage"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoyaltyReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getServiceFee"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidationCriteria"
  ): TypedContractMethod<[assetTypeId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCompatibleDeedNFT"
  ): TypedContractMethod<[deedNFT: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenWhitelisted"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "operatingAgreementName"
  ): TypedContractMethod<[uri: string], [string], "view">;
  getFunction(
    nameOrSignature: "registerOperatingAgreement"
  ): TypedContractMethod<[uri: string, name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeCompatibleDeedNFT"
  ): TypedContractMethod<[deedNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeWhitelistedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrimaryDeedNFT"
  ): TypedContractMethod<[deedNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoyaltyFeePercentage"
  ): TypedContractMethod<[percentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoyaltyReceiver"
  ): TypedContractMethod<[receiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServiceFee"
  ): TypedContractMethod<
    [token: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setValidationCriteria"
  ): TypedContractMethod<
    [assetTypeId: BigNumberish, criteria: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsAssetType"
  ): TypedContractMethod<[assetTypeId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "validateDeed"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "validateOperatingAgreement"
  ): TypedContractMethod<[operatingAgreement: string], [boolean], "view">;

  getEvent(
    key: "CompatibleDeedNFTUpdated"
  ): TypedContractEvent<
    CompatibleDeedNFTUpdatedEvent.InputTuple,
    CompatibleDeedNFTUpdatedEvent.OutputTuple,
    CompatibleDeedNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeedNFTUpdated"
  ): TypedContractEvent<
    DeedNFTUpdatedEvent.InputTuple,
    DeedNFTUpdatedEvent.OutputTuple,
    DeedNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeedValidated"
  ): TypedContractEvent<
    DeedValidatedEvent.InputTuple,
    DeedValidatedEvent.OutputTuple,
    DeedValidatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultOperatingAgreementUpdated"
  ): TypedContractEvent<
    DefaultOperatingAgreementUpdatedEvent.InputTuple,
    DefaultOperatingAgreementUpdatedEvent.OutputTuple,
    DefaultOperatingAgreementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FieldRequirementAdded"
  ): TypedContractEvent<
    FieldRequirementAddedEvent.InputTuple,
    FieldRequirementAddedEvent.OutputTuple,
    FieldRequirementAddedEvent.OutputObject
  >;
  getEvent(
    key: "FieldRequirementsCleared"
  ): TypedContractEvent<
    FieldRequirementsClearedEvent.InputTuple,
    FieldRequirementsClearedEvent.OutputTuple,
    FieldRequirementsClearedEvent.OutputObject
  >;
  getEvent(
    key: "OperatingAgreementRegistered"
  ): TypedContractEvent<
    OperatingAgreementRegisteredEvent.InputTuple,
    OperatingAgreementRegisteredEvent.OutputTuple,
    OperatingAgreementRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PrimaryDeedNFTUpdated"
  ): TypedContractEvent<
    PrimaryDeedNFTUpdatedEvent.InputTuple,
    PrimaryDeedNFTUpdatedEvent.OutputTuple,
    PrimaryDeedNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceFeeUpdated"
  ): TypedContractEvent<
    ServiceFeeUpdatedEvent.InputTuple,
    ServiceFeeUpdatedEvent.OutputTuple,
    ServiceFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWhitelistStatusUpdated"
  ): TypedContractEvent<
    TokenWhitelistStatusUpdatedEvent.InputTuple,
    TokenWhitelistStatusUpdatedEvent.OutputTuple,
    TokenWhitelistStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationCriteriaUpdated"
  ): TypedContractEvent<
    ValidationCriteriaUpdatedEvent.InputTuple,
    ValidationCriteriaUpdatedEvent.OutputTuple,
    ValidationCriteriaUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationError"
  ): TypedContractEvent<
    ValidationErrorEvent.InputTuple,
    ValidationErrorEvent.OutputTuple,
    ValidationErrorEvent.OutputObject
  >;

  filters: {
    "CompatibleDeedNFTUpdated(address,bool)": TypedContractEvent<
      CompatibleDeedNFTUpdatedEvent.InputTuple,
      CompatibleDeedNFTUpdatedEvent.OutputTuple,
      CompatibleDeedNFTUpdatedEvent.OutputObject
    >;
    CompatibleDeedNFTUpdated: TypedContractEvent<
      CompatibleDeedNFTUpdatedEvent.InputTuple,
      CompatibleDeedNFTUpdatedEvent.OutputTuple,
      CompatibleDeedNFTUpdatedEvent.OutputObject
    >;

    "DeedNFTUpdated(address)": TypedContractEvent<
      DeedNFTUpdatedEvent.InputTuple,
      DeedNFTUpdatedEvent.OutputTuple,
      DeedNFTUpdatedEvent.OutputObject
    >;
    DeedNFTUpdated: TypedContractEvent<
      DeedNFTUpdatedEvent.InputTuple,
      DeedNFTUpdatedEvent.OutputTuple,
      DeedNFTUpdatedEvent.OutputObject
    >;

    "DeedValidated(uint256,bool)": TypedContractEvent<
      DeedValidatedEvent.InputTuple,
      DeedValidatedEvent.OutputTuple,
      DeedValidatedEvent.OutputObject
    >;
    DeedValidated: TypedContractEvent<
      DeedValidatedEvent.InputTuple,
      DeedValidatedEvent.OutputTuple,
      DeedValidatedEvent.OutputObject
    >;

    "DefaultOperatingAgreementUpdated(string)": TypedContractEvent<
      DefaultOperatingAgreementUpdatedEvent.InputTuple,
      DefaultOperatingAgreementUpdatedEvent.OutputTuple,
      DefaultOperatingAgreementUpdatedEvent.OutputObject
    >;
    DefaultOperatingAgreementUpdated: TypedContractEvent<
      DefaultOperatingAgreementUpdatedEvent.InputTuple,
      DefaultOperatingAgreementUpdatedEvent.OutputTuple,
      DefaultOperatingAgreementUpdatedEvent.OutputObject
    >;

    "FieldRequirementAdded(uint256,string,string)": TypedContractEvent<
      FieldRequirementAddedEvent.InputTuple,
      FieldRequirementAddedEvent.OutputTuple,
      FieldRequirementAddedEvent.OutputObject
    >;
    FieldRequirementAdded: TypedContractEvent<
      FieldRequirementAddedEvent.InputTuple,
      FieldRequirementAddedEvent.OutputTuple,
      FieldRequirementAddedEvent.OutputObject
    >;

    "FieldRequirementsCleared(uint256)": TypedContractEvent<
      FieldRequirementsClearedEvent.InputTuple,
      FieldRequirementsClearedEvent.OutputTuple,
      FieldRequirementsClearedEvent.OutputObject
    >;
    FieldRequirementsCleared: TypedContractEvent<
      FieldRequirementsClearedEvent.InputTuple,
      FieldRequirementsClearedEvent.OutputTuple,
      FieldRequirementsClearedEvent.OutputObject
    >;

    "OperatingAgreementRegistered(string,string)": TypedContractEvent<
      OperatingAgreementRegisteredEvent.InputTuple,
      OperatingAgreementRegisteredEvent.OutputTuple,
      OperatingAgreementRegisteredEvent.OutputObject
    >;
    OperatingAgreementRegistered: TypedContractEvent<
      OperatingAgreementRegisteredEvent.InputTuple,
      OperatingAgreementRegisteredEvent.OutputTuple,
      OperatingAgreementRegisteredEvent.OutputObject
    >;

    "PrimaryDeedNFTUpdated(address)": TypedContractEvent<
      PrimaryDeedNFTUpdatedEvent.InputTuple,
      PrimaryDeedNFTUpdatedEvent.OutputTuple,
      PrimaryDeedNFTUpdatedEvent.OutputObject
    >;
    PrimaryDeedNFTUpdated: TypedContractEvent<
      PrimaryDeedNFTUpdatedEvent.InputTuple,
      PrimaryDeedNFTUpdatedEvent.OutputTuple,
      PrimaryDeedNFTUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ServiceFeeUpdated(address,uint256)": TypedContractEvent<
      ServiceFeeUpdatedEvent.InputTuple,
      ServiceFeeUpdatedEvent.OutputTuple,
      ServiceFeeUpdatedEvent.OutputObject
    >;
    ServiceFeeUpdated: TypedContractEvent<
      ServiceFeeUpdatedEvent.InputTuple,
      ServiceFeeUpdatedEvent.OutputTuple,
      ServiceFeeUpdatedEvent.OutputObject
    >;

    "TokenWhitelistStatusUpdated(address,bool)": TypedContractEvent<
      TokenWhitelistStatusUpdatedEvent.InputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputObject
    >;
    TokenWhitelistStatusUpdated: TypedContractEvent<
      TokenWhitelistStatusUpdatedEvent.InputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputObject
    >;

    "ValidationCriteriaUpdated(uint256,string)": TypedContractEvent<
      ValidationCriteriaUpdatedEvent.InputTuple,
      ValidationCriteriaUpdatedEvent.OutputTuple,
      ValidationCriteriaUpdatedEvent.OutputObject
    >;
    ValidationCriteriaUpdated: TypedContractEvent<
      ValidationCriteriaUpdatedEvent.InputTuple,
      ValidationCriteriaUpdatedEvent.OutputTuple,
      ValidationCriteriaUpdatedEvent.OutputObject
    >;

    "ValidationError(uint256,string)": TypedContractEvent<
      ValidationErrorEvent.InputTuple,
      ValidationErrorEvent.OutputTuple,
      ValidationErrorEvent.OutputObject
    >;
    ValidationError: TypedContractEvent<
      ValidationErrorEvent.InputTuple,
      ValidationErrorEvent.OutputTuple,
      ValidationErrorEvent.OutputObject
    >;
  };
}
