/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICreatorTokenLegacy,
  ICreatorTokenLegacyInterface,
} from "../../../../../@limitbreak/creator-token-standards/src/interfaces/ICreatorTokenLegacy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldValidator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newValidator",
        type: "address",
      },
    ],
    name: "TransferValidatorUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "getTransferValidator",
    outputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "setTransferValidator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICreatorTokenLegacy__factory {
  static readonly abi = _abi;
  static createInterface(): ICreatorTokenLegacyInterface {
    return new Interface(_abi) as ICreatorTokenLegacyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICreatorTokenLegacy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICreatorTokenLegacy;
  }
}
