/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICreatorToken,
  ICreatorTokenInterface,
} from "../../../../../@limitbreak/creator-token-standards/src/interfaces/ICreatorToken";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldValidator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newValidator",
        type: "address",
      },
    ],
    name: "TransferValidatorUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "getTransferValidationFunction",
    outputs: [
      {
        internalType: "bytes4",
        name: "functionSignature",
        type: "bytes4",
      },
      {
        internalType: "bool",
        name: "isViewFunction",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTransferValidator",
    outputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "setTransferValidator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICreatorToken__factory {
  static readonly abi = _abi;
  static createInterface(): ICreatorTokenInterface {
    return new Interface(_abi) as ICreatorTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICreatorToken {
    return new Contract(address, _abi, runner) as unknown as ICreatorToken;
  }
}
