#!/usr/bin/env sh
set -eu

: "${OP_PROPOSER_L1_ETH_RPC:?OP_PROPOSER_L1_ETH_RPC is required}"
: "${OP_PROPOSER_ROLLUP_RPC:=http://clear-op-node.railway.internal:8547}"
: "${OP_PROPOSER_GAME_FACTORY_ADDRESS:?OP_PROPOSER_GAME_FACTORY_ADDRESS is required}"
: "${OP_PROPOSER_PRIVATE_KEY:?OP_PROPOSER_PRIVATE_KEY is required}"

export OP_PROPOSER_POLL_INTERVAL="${OP_PROPOSER_POLL_INTERVAL:-20s}"
export OP_PROPOSER_PROPOSAL_INTERVAL="${OP_PROPOSER_PROPOSAL_INTERVAL:-3600s}"
export OP_PROPOSER_GAME_TYPE="${OP_PROPOSER_GAME_TYPE:-0}"
export OP_PROPOSER_ALLOW_NON_FINALIZED="${OP_PROPOSER_ALLOW_NON_FINALIZED:-true}"
export OP_PROPOSER_WAIT_NODE_SYNC="${OP_PROPOSER_WAIT_NODE_SYNC:-true}"

exec op-proposer \
  --rpc.port="${OP_PROPOSER_RPC_PORT:-8560}" \
  --log.level="${OP_PROPOSER_LOG_LEVEL:-info}" \
  --log.format=json
