/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721C } from "./ERC721C";
export type { ERC721CInitializable } from "./ERC721CInitializable";
